//------------------------------------------------------------------------------
// <auto-generated>
//    This code is auto-generated by a T4 template. This class can be only customized modifying the corresponding partial class.
//    All other changes to this file will cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using AutoMapper;

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Net;
using System.Reflection;
using System.Runtime.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

using Services.Core;
using Services.Db;
using Services.Dto;
using Services.Dto.internals;
using Services.Dto.Security;
using Services.Enums;
using Services.Models;
using Services.Schema;

using ServiceStack;
using ServiceStack.Text;

using Typed;
using Typed.Bindings;
using Typed.Notifications;
using Typed.Settings;

using Xtensive.Orm;
using Xtensive.Orm.Model;

using Attribute = Services.Dto.Attribute;
using ValueType = Services.Dto.ValueType;
using Version = Services.Dto.Version;
namespace Services.Enums
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum QuestionTypeEnm
    {
        [EnumMember(Value = DocConstantQuestionType.DATE)]
        DATE,
        [EnumMember(Value = DocConstantQuestionType.DATE_TIME)]
        DATE_TIME,
        [EnumMember(Value = DocConstantQuestionType.MEMO)]
        MEMO,
        [EnumMember(Value = DocConstantQuestionType.NUMBER)]
        NUMBER,
        [EnumMember(Value = DocConstantQuestionType.YES_NO)]
        YES_NO,
        [EnumMember(Value = DocConstantQuestionType.YES_NO_NA)]
        YES_NO_NA
    }
    
    public static partial class EnumExtensions
    {
        public static string ToEnumString(this QuestionTypeEnm instance)
        {
            switch(instance) 
            {
                case QuestionTypeEnm.DATE:
                    return DocConstantQuestionType.DATE;
                case QuestionTypeEnm.DATE_TIME:
                    return DocConstantQuestionType.DATE_TIME;
                case QuestionTypeEnm.MEMO:
                    return DocConstantQuestionType.MEMO;
                case QuestionTypeEnm.NUMBER:
                    return DocConstantQuestionType.NUMBER;
                case QuestionTypeEnm.YES_NO:
                    return DocConstantQuestionType.YES_NO;
                case QuestionTypeEnm.YES_NO_NA:
                    return DocConstantQuestionType.YES_NO_NA;
                default:
                    return string.Empty;
            }
        }
    }

    public sealed partial class DocConstantQuestionType : IEquatable<DocConstantQuestionType>, IEqualityComparer<DocConstantQuestionType>
    {
        public const string DATE = "Date";
        public const string DATE_TIME = "Date/Time";
        public const string MEMO = "Memo";
        public const string NUMBER = "Number";
        public const string YES_NO = "Yes/No";
        public const string YES_NO_NA = "Yes/No/Na";
        
        #region Internals
        
        private static List<string> _all;
        public static List<string> All => _all ?? (_all = typeof(DocConstantQuestionType).GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy).Where(fi => fi.IsLiteral && !fi.IsInitOnly).Select( fi => fi.GetRawConstantValue().ToString() ).OrderBy(n => n).ToList());

        private readonly string Value;

        private DocConstantQuestionType(string ItemName = null)
        {
            ItemName = ItemName ?? string.Empty;
            Value = FirstOrDefault(ItemName) ?? ItemName;
        }

        public static bool Contains(string name) => All.Any(val => string.Equals(val, name, StringComparison.OrdinalIgnoreCase));
        
        public static string FirstOrDefault(string name) => All.FirstOrDefault(val => string.Equals(val, name, StringComparison.OrdinalIgnoreCase));

        public static implicit operator DocConstantQuestionType(string Val) => new DocConstantQuestionType(Val);

        public static implicit operator string(DocConstantQuestionType item) => item?.Value ?? string.Empty;

        public override string ToString() => Value;

        #endregion Internals

        #region IEquatable

        public bool Equals(DocConstantQuestionType obj) => this == obj;

        public static bool operator ==(DocConstantQuestionType x, DocConstantQuestionType y) => DocTools.AreEqual(DocConvert.ToString(x), DocConvert.ToString(y));
        
        public bool Equals(DocConstantQuestionType x, DocConstantQuestionType y) => x == y;
        
        public static bool operator !=(DocConstantQuestionType x, DocConstantQuestionType y) => !(x == y);

        public override bool Equals(object obj)
        {
            var ret = false;
            if(!(obj is DocConstantQuestionType))
            {
                ret = false;
            }
            else
            {
                ret = this == (DocConstantQuestionType) obj;
            }
            return ret;
        }

        public override int GetHashCode() => 17 * Value?.GetHashCode() ?? -1;
                
        public int GetHashCode(DocConstantQuestionType obj) => obj?.GetHashCode() ?? -17;

        #endregion IEquatable
    }
}
