//------------------------------------------------------------------------------
// <auto-generated>
//    This code is auto-generated by a T4 template. This class can be only customized modifying the corresponding partial class.
//    All other changes to this file will cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Reflection;
using System.Runtime.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

using Services.Core;

using ServiceStack;

using SCDescript = System.ComponentModel.DescriptionAttribute;
using SCDisplay = System.ComponentModel.DataAnnotations.DisplayAttribute;
using SSDescript = ServiceStack.DataAnnotations.DescriptionAttribute;
namespace Services.Enums
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RiskOfBiasAssessmentEnm
    {
        [EnumMember(Value = DocConstantRiskOfBiasAssessment.NO), SCDescript(DocConstantRiskOfBiasAssessment.NO), SSDescript(DocConstantRiskOfBiasAssessment.NO), SCDisplay(Name = DocConstantRiskOfBiasAssessment.NO)]
        NO = 150784187,
        [EnumMember(Value = DocConstantRiskOfBiasAssessment.UNCLEAR), SCDescript(DocConstantRiskOfBiasAssessment.UNCLEAR), SSDescript(DocConstantRiskOfBiasAssessment.UNCLEAR), SCDisplay(Name = DocConstantRiskOfBiasAssessment.UNCLEAR)]
        UNCLEAR = 150784188,
        [EnumMember(Value = DocConstantRiskOfBiasAssessment.YES), SCDescript(DocConstantRiskOfBiasAssessment.YES), SSDescript(DocConstantRiskOfBiasAssessment.YES), SCDisplay(Name = DocConstantRiskOfBiasAssessment.YES)]
        YES = 150784186
    }
    
    public static partial class EnumExtensions
    {
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static string ToEnumString(this RiskOfBiasAssessmentEnm instance)
        {
            switch(instance)
            {
                case RiskOfBiasAssessmentEnm.NO:
                    return DocConstantRiskOfBiasAssessment.NO;
                case RiskOfBiasAssessmentEnm.UNCLEAR:
                    return DocConstantRiskOfBiasAssessment.UNCLEAR;
                case RiskOfBiasAssessmentEnm.YES:
                    return DocConstantRiskOfBiasAssessment.YES;
                default:
                    return string.Empty;
            }
        }

        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static string ToEnumString(this RiskOfBiasAssessmentEnm? instance)
        {
            if(null == instance) return string.Empty;
            return instance.Value.ToEnumString();
        }
    }

    public sealed partial class DocConstantRiskOfBiasAssessment : IEquatable<DocConstantRiskOfBiasAssessment>, IEqualityComparer<DocConstantRiskOfBiasAssessment>
    {
        public const string NO = "No";
        public const string UNCLEAR = "Unclear";
        public const string YES = "Yes";
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        private static List<string> _all;
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static List<string> All => _all ?? (_all = typeof(DocConstantRiskOfBiasAssessment).GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy).Where(fi => fi.IsLiteral && !fi.IsInitOnly).Select( fi => fi.GetRawConstantValue().ToString() ).OrderBy(n => n).ToList());
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        private readonly string Value;
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        private DocConstantRiskOfBiasAssessment(string ItemName = null)
        {
            ItemName = ItemName ?? string.Empty;
            Value = FirstOrDefault(ItemName) ?? ItemName;
        }
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static bool Contains(string name) => All.Any(val => string.Equals(val, name, StringComparison.OrdinalIgnoreCase));
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static string FirstOrDefault(string name) => All.FirstOrDefault(val => string.Equals(val, name, StringComparison.OrdinalIgnoreCase));
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static implicit operator DocConstantRiskOfBiasAssessment(string Val) => new DocConstantRiskOfBiasAssessment(Val);
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static implicit operator string(DocConstantRiskOfBiasAssessment item) => item?.Value ?? string.Empty;
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static explicit operator DocConstantRiskOfBiasAssessment(RiskOfBiasAssessmentEnm Val) => new DocConstantRiskOfBiasAssessment(Val.ToEnumString());
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static explicit operator RiskOfBiasAssessmentEnm(DocConstantRiskOfBiasAssessment item)
        {
            Enum.TryParse<RiskOfBiasAssessmentEnm>(item.ToString(), true, out var tryRet);
            return tryRet;
        }
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public override string ToString() => Value;
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public bool Equals(DocConstantRiskOfBiasAssessment obj) => this == obj;
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static bool operator ==(DocConstantRiskOfBiasAssessment x, DocConstantRiskOfBiasAssessment y) => DocTools.AreEqual(DocConvert.ToString(x), DocConvert.ToString(y));
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public bool Equals(DocConstantRiskOfBiasAssessment x, DocConstantRiskOfBiasAssessment y) => x == y;
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public static bool operator !=(DocConstantRiskOfBiasAssessment x, DocConstantRiskOfBiasAssessment y) => !(x == y);
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public override bool Equals(object obj)
        {
            var ret = false;
            if(!(obj is DocConstantRiskOfBiasAssessment))
            {
                ret = false;
            }
            else
            {
                ret = this == (DocConstantRiskOfBiasAssessment) obj;
            }
            return ret;
        }
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public override int GetHashCode() => 17 * Value?.GetHashCode() ?? -1;
        [GeneratedCodeAttribute("T4", "1.0.0.0")]
        public int GetHashCode(DocConstantRiskOfBiasAssessment obj) => obj?.GetHashCode() ?? -17;
    }
}
