
//------------------------------------------------------------------------------
// <auto-generated>
//    This code is auto-generated by a T4 template. This class can be only customized modifying the corresponding partial class.
//    All other changes to this file will cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;

using AutoMapper;

using Services.Core;
using Services.Db;
using Services.Dto;
using Services.Dto.internals;
using Services.Enums;

using ServiceStack;

using Xtensive.Orm;


namespace Services.Schema
{
    [TableMapping(DocConstantModelName.TERMSYNONYM)]
    public partial class DocEntityTermSynonym : DocEntityBase
    {
        private const string TERMSYNONYM_CACHE = "TermSynonymCache";
        public const ModelNameEnm CLASS_NAME = ModelNameEnm.TERMSYNONYM;
        
        #region Constructor
        public DocEntityTermSynonym(Session session) : base(session) {}

        public DocEntityTermSynonym() : base(new DocDbSession(Xtensive.Orm.Session.Current)) {}
        #endregion Constructor

        protected override List<string> _select => __vf ?? (__vf = DocWebSession.GetTypeSelect(new TermSynonym()));

        #region Static Members
        public static DocEntityTermSynonym Get(Reference reference)
        {
            return (true == (reference?.Id > 0)) ? Get(reference.Id) : null;
        }

        public static DocEntityTermSynonym Get(int? primaryKey, bool noCache, DocQuery query)
        {
            if(!(primaryKey > 0)) return null;
            return query.SelectAll<DocEntityTermSynonym>().FirstOrDefault(e => e.Id == primaryKey.Value);
        }

        public static DocEntityTermSynonym Get(int? primaryKey)
        {
            var query = DocQuery.ActiveQuery;
            if(null == primaryKey) return null;
            var ret = DocEntityThreadCache<DocEntityTermSynonym>.GetFromCache(primaryKey, TERMSYNONYM_CACHE);
            if(null == ret)
            {
                ret = query.SelectAll<DocEntityTermSynonym>().Where(e => e.Id == primaryKey.Value).FirstOrDefault();
                if(null != ret) 
                {
                    DocEntityThreadCache<DocEntityTermSynonym>.UpdateCache(ret.Id, ret, TERMSYNONYM_CACHE);
                    DocEntityThreadCache<DocEntityTermSynonym>.UpdateCache(ret.Hash, ret, TERMSYNONYM_CACHE);
                }
            }
            return ret;
        }

        public static DocEntityTermSynonym Get(Guid hash)
        {
            var query = DocQuery.ActiveQuery;
            var ret = DocEntityThreadCache<DocEntityTermSynonym>.GetFromCache(hash, TERMSYNONYM_CACHE);
            
            if(null == ret)
            {
                ret = query.SelectAll<DocEntityTermSynonym>().Where(e => e.Hash == hash).FirstOrDefault();
                if(null != ret) 
                {
                    DocEntityThreadCache<DocEntityTermSynonym>.UpdateCache(ret.Id, ret, TERMSYNONYM_CACHE);
                    DocEntityThreadCache<DocEntityTermSynonym>.UpdateCache(ret.Hash, ret, TERMSYNONYM_CACHE);
                }
            }
            return ret;
        }
        #endregion Static Members

        #region Properties
        [Field]
        public bool Approved { get; set; }


        [Field]
        public DocEntitySet<DocEntityLookupTableBinding> Bindings { get; private set; }


        public List<int> BindingsIds => Bindings.Select(e => e.Id).ToList();


        public int? BindingsCount { get { return Bindings.Count(); } private set { var noid = value; } }


        [Field(Nullable = false)]
        public DocEntityTermMaster Master { get; set; }
        public int? MasterId { get { return Master?.Id; } private set { var noid = value; } }


        [Field]
        public bool Preferred { get; set; }


        [Field]
        public DocEntityScope Scope { get; set; }
        public int? ScopeId { get { return Scope?.Id; } private set { var noid = value; } }


        [Field(Nullable = false, Length = 800)]
        public string Synonym { get; set; }



        [Field]
        public override string Gestalt { get; set; }

        [Field(DefaultValue = 0), Version(VersionMode.Manual)]
        public override int VersionNo { get; set; }

        [Field]
        public override DateTime? Created { get; set; }

        [Field]
        public override DateTime? Updated { get; set; }

        [Field(DefaultValue = false), FieldMapping(nameof(Locked))]
        public override bool Locked { get; set; }

        [Field(DefaultValue = false), FieldMapping(nameof(Archived))]
        public override bool Archived { get; set; }

        #endregion Properties

        #region Overrides of DocEntity

        public override ModelNameEnm ClassName => CLASS_NAME;

        public override DocConstantModelName TableName => CLASS_NAME.ToEnumString();

        public const string CACHE_KEY_PREFIX = "FindTermSynonyms";

        #endregion Overrides of DocEntity

        #region Entity overrides
        /// <summary>
        ///    Called when entity is about to be removed.
        /// </summary>
        protected override void OnRemoving()
        {
            base.OnRemoving();

            FlushCache();
        }

        /// <summary>
        ///    Called when entity should be validated. Override this method to perform custom object validation.
        /// </summary>
        protected override void OnValidate()
        {
            if (false == ValidationMessage.IsValid)
            {
                throw new HttpError(HttpStatusCode.Conflict, $"TermSynonym requires: {ValidationMessage.Message}.");
            }

            base.OnValidate();
            _validated = true;
        }

        public override IDocEntity SaveChanges(bool ignoreCache, DocConstantPermission permission)
        {
            Synonym = Synonym?.TrimAndPruneSpaces();
            return base.SaveChanges(ignoreCache, permission);
        }

        public override IDocEntity SaveChanges(bool ignoreCache) => SaveChanges(ignoreCache, DocConstantPermission.EDIT);
        public override IDocEntity SaveChanges(DocConstantPermission permission) => SaveChanges(false, DocConstantPermission.EDIT);
        public override IDocEntity SaveChanges() => SaveChanges(DocConstantPermission.EDIT);

        public override void FlushCache()
        {
            base.FlushCache();
            DocCacheClient.RemoveById(Id);
        }
        #endregion Entity overrides

        #region Validation
        public DocValidationMessage ValidationMessage
        {
            get
            {
                var isValid = true;
                var message = string.Empty;

                if(DocTools.IsNullOrEmpty(Master))
                {
                    isValid = false;
                    message += " Master is a required property.";
                }
                if(DocTools.IsNullOrEmpty(Synonym))
                {
                    isValid = false;
                    message += " Synonym is a required property.";
                }

                var ret = new DocValidationMessage(message, isValid);
                return ret;
            }
        }
        #endregion Validation

        #region Converters

        public TermSynonym ToDto() => Mapper.Map<DocEntityTermSynonym, TermSynonym>(this);

        public static explicit operator TermSynonym(DocEntityTermSynonym en) => en?.ToDto();

        public override IDto ToIDto() => ToDto();
        #endregion Converters
    }
}
