
//------------------------------------------------------------------------------
// <auto-generated>
//    This code is auto-generated by a T4 template. This class can be only customized modifying the corresponding partial class.
//    All other changes to this file will cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;

using AutoMapper;

using Services.Core;
using Services.Db;
using Services.Dto;
using Services.Dto.internals;
using Services.Enums;

using ServiceStack;

using Xtensive.Orm;

using Attribute = Services.Dto.Attribute;


namespace Services.Schema
{
    [TableMapping(DocConstantModelName.ATTRIBUTE)]
    public partial class DocEntityAttribute : DocEntityBase
    {
        private const string ATTRIBUTE_CACHE = "AttributeCache";
        public const ModelNameEnm CLASS_NAME = ModelNameEnm.ATTRIBUTE;

        public DocEntityAttribute(Session session) : base(session) {}

        public DocEntityAttribute() : base(new DocDbSession(Xtensive.Orm.Session.Current)) {}

        protected override List<string> _select => __vf ?? (__vf = DocWebSession.GetTypeSelect(new Attribute()));
        public static DocEntityAttribute Get(Reference reference)
        {
            return (true == (reference?.Id > 0)) ? Get(reference.Id) : null;
        }

        public static DocEntityAttribute Get(int? primaryKey, bool noCache, DocQuery query)
        {
            if(!(primaryKey > 0)) return null;
            return query.SelectAll<DocEntityAttribute>().FirstOrDefault(e => e.Id == primaryKey.Value);
        }

        public static DocEntityAttribute Get(int? primaryKey)
        {
            var query = DocQuery.ActiveQuery;
            if(null == primaryKey) return null;
            var ret = DocEntityThreadCache<DocEntityAttribute>.GetFromCache(primaryKey, ATTRIBUTE_CACHE);
            if(null == ret)
            {
                ret = query.SelectAll<DocEntityAttribute>().Where(e => e.Id == primaryKey.Value).FirstOrDefault();
                if(null != ret) 
                {
                    DocEntityThreadCache<DocEntityAttribute>.UpdateCache(ret.Id, ret, ATTRIBUTE_CACHE);
                    DocEntityThreadCache<DocEntityAttribute>.UpdateCache(ret.Hash, ret, ATTRIBUTE_CACHE);
                }
            }
            return ret;
        }

        public static DocEntityAttribute Get(Guid hash)
        {
            var query = DocQuery.ActiveQuery;
            var ret = DocEntityThreadCache<DocEntityAttribute>.GetFromCache(hash, ATTRIBUTE_CACHE);
            
            if(null == ret)
            {
                ret = query.SelectAll<DocEntityAttribute>().Where(e => e.Hash == hash).FirstOrDefault();
                if(null != ret) 
                {
                    DocEntityThreadCache<DocEntityAttribute>.UpdateCache(ret.Id, ret, ATTRIBUTE_CACHE);
                    DocEntityThreadCache<DocEntityAttribute>.UpdateCache(ret.Hash, ret, ATTRIBUTE_CACHE);
                }
            }
            return ret;
        }

        [Field(Nullable = false)]
        public DocEntityLookupTable AttributeName { get; set; }
        public int? AttributeNameId { get { return AttributeName?.Id; } private set { var noid = value; } }


        [Field]
        public DocEntityLookupTable AttributeType { get; set; }
        public int? AttributeTypeId { get { return AttributeType?.Id; } private set { var noid = value; } }


        [Field(Nullable = false)]
        public DocEntityAttributeInterval Interval { get; set; }
        public int? IntervalId { get { return Interval?.Id; } private set { var noid = value; } }


        [Field(Nullable = false, DefaultValue = false)]
        public bool IsCharacteristic { get; set; }


        [Field(Nullable = false, DefaultValue = false)]
        public bool IsOutcome { get; set; }


        [Field(DefaultValue = false)]
        public bool? IsPositive { get; set; }


        [Field]
        public string UniqueKey { get; set; }


        [Field(Nullable = false)]
        public DocEntityValueType ValueType { get; set; }
        public int? ValueTypeId { get { return ValueType?.Id; } private set { var noid = value; } }



        [Field]
        public override string Gestalt { get; set; }

        [Field(DefaultValue = 0), Version(VersionMode.Manual)]
        public override int VersionNo { get; set; }

        [Field]
        public override DateTime? Created { get; set; }

        [Field]
        public override DateTime? Updated { get; set; }

        [Field(DefaultValue = false), FieldMapping(nameof(Locked))]
        public override bool Locked { get; set; }

        [Field(DefaultValue = false), FieldMapping(nameof(Archived))]
        public override bool Archived { get; set; }


        public override ModelNameEnm ClassName => CLASS_NAME;
        public override DocConstantModelName TableName => CLASS_NAME.ToEnumString();

        public const string CACHE_KEY_PREFIX = "FindAttributes";

        /// <summary>
        ///    Called when entity is about to be removed.
        /// </summary>
        protected override void OnRemoving()
        {
            base.OnRemoving();

            FlushCache();
        }

        /// <summary>
        ///    Called when entity should be validated. Override this method to perform custom object validation.
        /// </summary>
        protected override void OnValidate()
        {
            if (false == ValidationMessage.IsValid)
            {
                throw new HttpError(HttpStatusCode.Conflict, $"Attribute requires: {ValidationMessage.Message}.");
            }

            base.OnValidate();
            _validated = true;
        }

        public override IDocEntity SaveChanges(bool ignoreCache, DocConstantPermission permission)
        {
            UniqueKey = UniqueKey?.TrimAndPruneSpaces();
            return base.SaveChanges(ignoreCache, permission);
        }

        public override IDocEntity SaveChanges(bool ignoreCache) => SaveChanges(ignoreCache, DocConstantPermission.EDIT);
        public override IDocEntity SaveChanges(DocConstantPermission permission) => SaveChanges(false, DocConstantPermission.EDIT);
        public override IDocEntity SaveChanges() => SaveChanges(DocConstantPermission.EDIT);

        public override void FlushCache()
        {
            base.FlushCache();

        }

        public DocValidationMessage ValidationMessage
        {
            get
            {
                var isValid = true;
                var message = string.Empty;

                if(DocTools.IsNullOrEmpty(AttributeName))
                {
                    isValid = false;
                    message += " AttributeName is a required property.";
                }
                else
                {
                    if(AttributeName.Enum?.Name != "AttributeName")
                    {
                        isValid = false;
                        message += " AttributeName is a " + AttributeName.Enum.Name + ", but must be a AttributeName.";
                    }
                }
                if(null != AttributeType && AttributeType?.Enum?.Name != "AttributeType")
                {
                    isValid = false;
                    message += " AttributeType is a " + AttributeType?.Enum?.Name + ", but must be a AttributeType.";
                }
                if(DocTools.IsNullOrEmpty(Interval))
                {
                    isValid = false;
                    message += " Interval is a required property.";
                }
                if(DocTools.IsNullOrEmpty(IsCharacteristic))
                {
                    isValid = false;
                    message += " IsCharacteristic is a required property.";
                }
                if(DocTools.IsNullOrEmpty(IsOutcome))
                {
                    isValid = false;
                    message += " IsOutcome is a required property.";
                }
                if(DocTools.IsNullOrEmpty(ValueType))
                {
                    isValid = false;
                    message += " ValueType is a required property.";
                }

                var ret = new DocValidationMessage(message, isValid);
                return ret;
            }
        }

        public Attribute ToDto() => Mapper.Map<DocEntityAttribute, Attribute>(this);

        public static explicit operator Attribute(DocEntityAttribute en) => en?.ToDto();

        public override IDto ToIDto() => ToDto();
    }
}
